apiVersion: v1
kind: Service
metadata:
  name: openhands-service
  namespace: openhands-poc
  labels:
    app: openhands
spec:
  selector:
    app: openhands
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openhands-route
  namespace: openhands-poc
  labels:
    app: openhands
spec:
  to:
    kind: Service
    name: openhands-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
