apiVersion: v1
kind: ConfigMap
metadata:
  name: openhands-config
  namespace: openhands-poc
data:
  # RHOAI LLM endpoint - using same endpoint as product-recommender-system
  llm_base_url: "https://llama-3-1-8b-instruct-predictor-kickstart-llms.apps.ai-dev02.kni.syseng.devcluster.openshift.com/v1"
  llm_model: "meta-llama/Llama-3.1-8B-Instruct"
  # OpenHands specific configuration - use local for OpenShift
  sandbox_type: "local"
  max_iterations: "100"
  max_budget_per_task: "10.0"
  enable_auto_lint: "true"
  enable_auto_test: "true"
  file_store_path: "/opt/workspace_base/.openhands"
---
apiVersion: v1
kind: Secret
metadata:
  name: openhands-secrets
  namespace: openhands-poc
type: Opaque
data:
  # Base64 encoded API key for RHOAI model serving
  # Empty API key - LLM endpoint is publicly accessible (same as product-recommender-system)
  llm_api_key: "c2stZHVtbXkta2V5LWZvci1wdWJsaWMtZW5kcG9pbnQ="  # Base64: sk-dummy-key-for-public-endpoint
---
apiVersion: v1
kind: Namespace
metadata:
  name: openhands-poc
  labels:
    name: openhands-poc
    opendatahub.io/dashboard: "true"
